[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "W", "I", "N", "UP"]
ignore = ["N999"]  # Игнорируем предупреждение о стиле именования модулей

[tool.ruff.lint.isort]
known-first-party = ["server"]

